//! Mock Counter daemon used across executor tests.
//!
//! The Counter channel has four operations:
//!
//! - `Increment(u32)` -- lowers to one `Assert`.
//! - `Decrement(u32)` -- lowers to one `Retract`.
//! - `Query` -- lowers to one `Match`.
//! - `ResetTracking` -- lowers to zero Sema operations (daemon-side
//!   bookkeeping only); witnesses the empty-lowering path.
//!
//! Rejection: `Increment(0)` and `Decrement(0)` are rejected at the
//! lowering stage with `CounterReply::Rejected(CounterRejection::ZeroMagnitude)`
//! so we witness domain rejection carried in the contract reply
//! vocabulary without calling the engine.
//!
//! Engine: `CounterEngine` returns canned effects shaped to mirror
//! the operation classes (`Wrote` for Assert/Mutate/Retract, `Read`
//! for Match). `CounterEngine::with_poison()` returns an engine
//! that always returns `Err(PoisonError)` so we witness engine
//! rejection.

use rkyv::{Archive, Deserialize as RkyvDeserialize, Serialize as RkyvSerialize};
use signal_executor::{Lowering, SemaEffect, SemaEffectOutcome, SemaEngine};
use signal_frame::RequestPayload;
use signal_sema::SemaOperation;
use thiserror::Error;

/// Counter channel operation set. Stand-in for a contract's
/// operation enum (which would be generated by `signal_channel!`).
#[derive(Archive, RkyvSerialize, RkyvDeserialize, Debug, Clone, PartialEq, Eq)]
pub enum CounterOperation {
    Increment(u32),
    Decrement(u32),
    Query,
    ResetTracking,
}

impl RequestPayload for CounterOperation {}

/// Counter channel reply set. Stand-in for a contract's reply
/// enum (which would be generated by `signal_channel!`).
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CounterReply {
    Incremented { rows_written: u64 },
    Decremented { rows_matched: u64 },
    Queried { rows_read: u64 },
    TrackingReset,
    Rejected(CounterRejection),
}

/// Counter-side domain rejection detail carried by
/// `CounterReply::Rejected`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CounterRejection {
    ZeroMagnitude,
}

/// Counter lowering. Each operation lowers in a fixed sequence
/// declared by the impl.
pub struct CounterLowering;

impl CounterLowering {
    pub fn new() -> Self {
        Self
    }
}

impl Default for CounterLowering {
    fn default() -> Self {
        Self::new()
    }
}

impl Lowering for CounterLowering {
    type Operation = CounterOperation;
    type Reply = CounterReply;

    fn lower(&self, operation: &Self::Operation) -> Result<Vec<SemaOperation>, Self::Reply> {
        match operation {
            CounterOperation::Increment(magnitude) | CounterOperation::Decrement(magnitude)
                if *magnitude == 0 =>
            {
                Err(CounterReply::Rejected(CounterRejection::ZeroMagnitude))
            }
            CounterOperation::Increment(_) => Ok(vec![SemaOperation::Assert]),
            CounterOperation::Decrement(_) => Ok(vec![SemaOperation::Retract]),
            CounterOperation::Query => Ok(vec![SemaOperation::Match]),
            CounterOperation::ResetTracking => Ok(Vec::new()),
        }
    }

    fn reply_from_effects(
        &self,
        operation: &Self::Operation,
        effects: &[SemaEffect],
    ) -> Self::Reply {
        match operation {
            CounterOperation::Increment(_) => {
                let rows_written = first_wrote_for(effects, SemaOperation::Assert);
                CounterReply::Incremented { rows_written }
            }
            CounterOperation::Decrement(_) => {
                let rows_matched = first_matched_for(effects, SemaOperation::Retract);
                CounterReply::Decremented { rows_matched }
            }
            CounterOperation::Query => {
                let rows_read = first_read_for(effects, SemaOperation::Match);
                CounterReply::Queried { rows_read }
            }
            CounterOperation::ResetTracking => CounterReply::TrackingReset,
        }
    }
}

fn first_wrote_for(effects: &[SemaEffect], wanted: SemaOperation) -> u64 {
    effects
        .iter()
        .find_map(|effect| match (effect.operation, &effect.outcome) {
            (operation, SemaEffectOutcome::Wrote { rows_written, .. }) if operation == wanted => {
                Some(*rows_written)
            }
            _ => None,
        })
        .unwrap_or(0)
}

fn first_matched_for(effects: &[SemaEffect], wanted: SemaOperation) -> u64 {
    effects
        .iter()
        .find_map(|effect| match (effect.operation, &effect.outcome) {
            (operation, SemaEffectOutcome::Wrote { rows_matched, .. }) if operation == wanted => {
                Some(*rows_matched)
            }
            _ => None,
        })
        .unwrap_or(0)
}

fn first_read_for(effects: &[SemaEffect], wanted: SemaOperation) -> u64 {
    effects
        .iter()
        .find_map(|effect| match (effect.operation, &effect.outcome) {
            (operation, SemaEffectOutcome::Read { rows_read }) if operation == wanted => {
                Some(*rows_read)
            }
            _ => None,
        })
        .unwrap_or(0)
}

/// Mock Sema engine for tests. Returns canned effects shaped to
/// mirror operation classes. Counts committed operations for
/// assertions in tests that need to observe whether the engine
/// was called at all.
pub struct CounterEngine {
    committed: u64,
    poisoned: bool,
}

impl CounterEngine {
    pub fn new() -> Self {
        Self {
            committed: 0,
            poisoned: false,
        }
    }

    pub fn with_poison() -> Self {
        Self {
            committed: 0,
            poisoned: true,
        }
    }

    pub fn committed_operation_count(&self) -> u64 {
        self.committed
    }
}

impl Default for CounterEngine {
    fn default() -> Self {
        Self::new()
    }
}

impl SemaEngine for CounterEngine {
    type Error = PoisonError;

    fn execute_atomic(
        &mut self,
        operations: Vec<SemaOperation>,
    ) -> Result<Vec<SemaEffect>, Self::Error> {
        if self.poisoned {
            return Err(PoisonError);
        }
        let effects: Vec<SemaEffect> = operations
            .into_iter()
            .map(|operation| match operation {
                SemaOperation::Assert => SemaEffect::new(
                    operation,
                    SemaEffectOutcome::Wrote {
                        rows_written: 1,
                        rows_matched: 0,
                    },
                ),
                SemaOperation::Mutate | SemaOperation::Retract => SemaEffect::new(
                    operation,
                    SemaEffectOutcome::Wrote {
                        rows_written: 1,
                        rows_matched: 1,
                    },
                ),
                SemaOperation::Match => {
                    SemaEffect::new(operation, SemaEffectOutcome::Read { rows_read: 7 })
                }
                SemaOperation::Subscribe => SemaEffect::new(
                    operation,
                    SemaEffectOutcome::Stream {
                        subscription_token: 42,
                    },
                ),
                SemaOperation::Validate => SemaEffect::new(
                    operation,
                    SemaEffectOutcome::Validated {
                        predicate_held: true,
                    },
                ),
            })
            .collect();
        self.committed += effects.len() as u64;
        Ok(effects)
    }
}

/// Sentinel engine error for the poison test.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Error)]
#[error("engine poisoned for test")]
pub struct PoisonError;
